import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import HeaderTop from "@/components/layout/headerTop";
import '../sass/index.scss'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div  className={inter.className}>
          <HeaderTop />
          <Header />
          <main className='content'>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
